### PR TITLE
Sig 3795 Add SignhostClientLibrary version updated.

### PR DESCRIPTION
**Pull request by ilkedgn**
v1:
 Version changed.
 Tests updated.

### CODE REVIEW

**Review by evoronkin — APPROVED** [review]
Tech approved commit 14cefcd8a7e74e2e2088e216872e856b561287b5

**Review by BerendJonkman — APPROVED** [review]
Approved technical review - `14cefcd8a7e74e2e2088e216872e856b561287b5`

**Review by BerendJonkman — APPROVED** [review]
Approved technical review - `14cefcd8a7e74e2e2088e216872e856b561287b5`

**Comment by ATimmeh33** [comment]
Guideline review approved 139627c7537693f1c01fd08b60eb3c4036317a9c

**Review by ATimmeh33 — APPROVED** [review]
Guideline review approved 139627c7537693f1c01fd08b60eb3c4036317a9c

**Pull request merged**
